version: "3"
services:
    db:
        image: postgres:12-alpine
        restart: always
        ports:
            - 54320:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
        env_file:
            - ./.env.local

volumes:
    pg_data:
